#ifndef BLOCKTYPE_0
#define BLOCKTYPE_0

#include <stdio.h>

#define BLOCKTYPE0_SUCCESS 0
#define BLOCKTYPE0_HEADER_FAILURE 1
#define BLOCKTYPE0_INVALID_INPUT 2
#define BLOCKTYPE0_MALLOC_FAILURE 3
#define BLOCKTYPE0_READ_FAILURE 4
#define BLOCKTYPE0_WRITING_FAILURE 5
#define BLOCKTYPE0_FOOTER_FAILURE 6

#define MAX_SIZE 65535

#define IS_LAST_BIT 0x01
#define IS_LAST_NUM_BITS 1

#define BTYPE0 0x00
#define BTYPE0_NUM_BITS 2

#define HEADER_PADDING 0x00
#define HEADER_PADDING_NUM_BITS 5

int blocktype0_encoding(FILE *input_file, FILE *output_file);

#endif
